name: Build Spectrum
description: Setup the proper jdk container

inputs:
  args:
    description: Additional Maven arguments
    default: ''

  profiles:
    description: Active Maven profiles
    default: all

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4.0.0
      with:
        java-version: 21
        distribution: temurin
        cache: maven

    - name: Building Spectrum
      shell: bash
      run: >
        ./mvnw install
        -DskipSign
        -Dmaven.plugin.validation=BRIEF
        ${{ inputs.args }}
        -ntp
        -P ${{ inputs.profiles }}
