name: Build Spectrum
description: Setup the proper jdk container

inputs:
  skipTests:
    description: Skips unit tests
    required: true
    default: false

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4.0.0
      with:
        java-version: 21
        distribution: temurin
        cache: maven

    - name: Building Spectrum
      shell: bash
      run: ./mvnw install -DskipTests=${{ inputs.skipTests }} -DskipSign -Dmaven.plugin.validation=BRIEF -ntp -pl spectrum
