name: Build Spectrum
description: Builds just the framework, skipping unit tests

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4.0.0
      with:
        java-version: 21
        distribution: temurin
        cache: maven

    - name: Building Spectrum
      shell: bash
      run: ./mvnw install -DskipSign -Dmaven.plugin.validation=NONE -DskipTests -ntp -pl spectrum
