name: Run in Java
description: Setup the proper jdk container
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4.0.0
      with:
        java-version: 21
        distribution: temurin
        cache: maven