name: Free Disk Space
description: removes files not needed from ubuntu-latest image, to get rid of GH action warning

runs:
  using: composite
  steps:
    - name: Free Disk Space
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
