# Common vars to interpolate other String values in the configuration
vars:
  downloadsFolder: ${user.dir}\target\downloads # Path, as you can see below, where to save downloaded files

# Variables related to the runtime environment, meaning the machine where the tests will run, for example your local pc or a remote server
runtime:
  profiles: ${spectrum.profiles:-local} # profiles to be activated. By default, it's 'local', so the configuration-local.yaml will be loaded (if present). This property is read only from the base configuration.yaml: it doesn't make sense to change it in a profile-specific file
  browser: ${spectrum.browser:-chrome}  # browser to use
  environment: # Runtime environment. Can be local or grid
    local: { }
  filesFolder: src/test/resources/files # folder where you will store files to be checked against downloaded ones
  downloadsFolder: ${downloadsFolder}

# Application under test
application:
  baseUrl: http://localhost:8080

# TestBook (coverage)
testBook: null

# Execution video recording
video:
  frames: [ ] # by default, nothing is recorded

# Extent Report configuration
extent:
  documentTitle: Spectrum Report  # Title of the html page
  reportFolder: target/spectrum/reports # Where to generate the report
  reportName: Spectrum Report   # Name shown in the header of the report
  fileName: spectrum-report-{timestamp}.html  # you can use the {timestamp} placeholder, which will be resolved at runtime
  theme: STANDARD   # Theme used. Can be STANDARD or DARK
  timeStampFormat: EEEE dd/MM/yyyy, hh:mm a (zzz)   # Timestamp of each test's start-time and end-time

# WebDriver configuration
webDriver:
  waits:
    implicit: 0    # Seconds Selenium waits before throwing a NoSuchElementException when an element isn't found.
    pageLoadTimeout: 10   # Seconds that Selenium waits before throwing an exception because the page wasn't fully loaded yet.
    scriptTimeout: 10   # Seconds that Selenium waits before throwing a ScriptTimeoutException.
    downloadTimeout: 15   # FluentWait injected in test classes/pages that you can use on file download.

  # Chrome capabilities. See: https://chromedriver.chromium.org/capabilities
  chrome:
    args: [ ]
    capabilities:
      prefs:
        download.prompt_for_download: false
        download.directory_upgrade: true
        download.default_directory: ${downloadsFolder}
        safebrowsing.enabled: true

  # Firefox capabilities. See: https://developer.mozilla.org/en-US/docs/Web/WebDriver/Capabilities/firefoxOptions
  firefox:
    args: [ ]
    logLevel: ERROR
    preferences:
      browser.download.folderList: 2
      browser.download.useDownloadDir: true
      browser.download.dir: ${downloadsFolder}
      browser.helperApps.neverAsk.saveToDisk: application/pdf
      pdfjs.disabled: true

  # Edge capabilities. See: https://learn.microsoft.com/en-us/microsoft-edge/webDriver-chromium/capabilities-edge-options
  edge:
    args: [ ]
    capabilities:
      prefs:
        download.default_directory: ${downloadsFolder}

  # WebDriver's internal logging levels
  logs:
    level: DEBUG  # The level at which webDriver's logs will be logged
    browser: SEVERE
    driver: SEVERE
    performance: OFF

  # Events fired by the webDriver, automatically logged and added to the report according to the log level set when running the suite. Specify a level among OFF, TRACE, DEBUG, INFO, WARN.
  events:
    beforeAnyCall:
      message: About to call method %2$s with args %3$s on target %1$s
    afterAnyCall:
      message: Called method method %2$s with args %3$s on target %1$s with result %4$s
    onError:
      level: DEBUG
      message: Got a %4$s calling method %2$s with args %3$s on target %1$s
    beforeAnyWebDriverCall:
      message: About to call %2$s with args %3$s
    afterAnyWebDriverCall:
      message: Called %2$s with args %3$s with result %4$s
    beforeGet:
      level: INFO
      message: About to get <a href="%2$s" target="_blank">%2$s</a>
    afterGet:
      message: Got <a href="%2$s" target="_blank">%2$s</a>
    beforeGetCurrentUrl:
      message: About to get current url
    afterGetCurrentUrl:
      message: Got current url with result %1$s
    beforeGetTitle:
      message: About to get title
    afterGetTitle:
      message: Got title %2$s
    beforeFindElement:
      level: DEBUG
      message: About to find element %2$s
    afterFindElement:
      message: Element %2$s is %3$s
    beforeFindElements:
      level: DEBUG
      message: About to find elements %2$s
    afterFindElements:
      message: Elements %2$s are %3$s
    beforeGetPageSource:
      message: About to get page source
    afterGetPageSource:
      level: DEBUG
      message: Page source is:<br/><pre style="max-height:200px; overflow:auto; overflow-x:hidden;">%2$s</pre>
    beforeClose:
      level: DEBUG
      message: About to close
    afterClose:
      message: Closed
    beforeQuit:
      level: DEBUG
      message: About to quit
    afterQuit:
      message: Done quitting
    beforeGetWindowHandles:
      level: DEBUG
      message: About to get window handles
    afterGetWindowHandles:
      message: Got window handles %2$s
    beforeGetWindowHandle:
      level: DEBUG
      message: About to get window handle
    afterGetWindowHandle:
      message: Got window handle %2$s
    beforeExecuteScript:
      level: DEBUG
      message: About to execute script %2$s with args %3$s
    afterExecuteScript:
      message: Result of script %2$s with args %3$s is %4$s
    beforeExecuteAsyncScript:
      level: DEBUG
      message: About to execute async script %2$s with args %3$s
    afterExecuteAsyncScript:
      message: Result of async script %2$s with args %3$s is %4$s
    beforePerform:
      level: DEBUG
      message: About to perform actions %2$s
    afterPerform:
      message: Performed actions %2$s
    beforeResetInputState:
      message: About to reset input state
    afterResetInputState:
      message: Done resetting input state
    beforeAnyWebElementCall:
      message: About to call %2$s with args %3$s on %1$s
    afterAnyWebElementCall:
      message: Result of call %2$s with args %3$s on %1$s is %4$s
    beforeClick:
      level: INFO
      message: Clicking on %1$s
    afterClick:
      message: Clicked on %1$s
    beforeSubmit:
      level: INFO
      message: Submitting %1$s
    afterSubmit:
      message: Submitted %1$s
    beforeSendKeys:
      level: INFO
      message: Sending keys %2$s to %1$s
    afterSendKeys:
      message: Sent keys %2$s to %1$s
    beforeClear:
      level: DEBUG
      message: Clearing %1$s
    afterClear:
      message: Cleared %1$s
    beforeGetTagName:
      message: Getting tag name of %1$s
    afterGetTagName:
      level: INFO
      message: Tag name of %1$s is %2$s
    beforeGetAttribute:
      message: Getting attribute %2$s of %1$s
    afterGetAttribute:
      level: INFO
      message: Attribute %2$s of %1$s is %3$s
    beforeIsSelected:
      message: Checking if %1$s is selected
    afterIsSelected:
      level: INFO
      message: Element %1$s is selected? %2$s
    beforeIsEnabled:
      message: Checking if %1$s is enabled
    afterIsEnabled:
      level: INFO
      message: Element %1$s is enabled? %2$s
    beforeGetText:
      message: Getting text of %1$s
    afterGetText:
      level: INFO
      message: Text of %1$s is %2$s
    beforeFindWebElement:
      level: DEBUG
      message: About to find element %2$s inside %1$s
    afterFindWebElement:
      message: Element %2$s inside %1$s is %3$s
    beforeFindWebElements:
      level: DEBUG
      message: About to find elements %2$s inside %1$s
    afterFindWebElements:
      message: Elements %2$s inside %1$s are %3$s
    beforeIsDisplayed:
      message: Checking if %1$s is displayed
    afterIsDisplayed:
      level: INFO
      message: Element %1$s is displayed? %2$s
    beforeGetLocation:
      message: Getting location of %1$s
    afterGetLocation:
      level: INFO
      message: Location of %1$s is %2$s
    beforeGetSize:
      message: Getting size of %1$s
    afterGetSize:
      level: INFO
      message: Size of %1$s is %2$s
    beforeGetCssValue:
      message: Getting css property %2$s of element %1$s
    afterGetCssValue:
      level: INFO
      message: Css property %2$s of element %1$s is %3$s
    beforeAnyNavigationCall:
      message: Calling navigation method %2$s with args %3$s
    afterAnyNavigationCall:
      message: Navigation method %2$s with args %3$s led to %4$s
    beforeTo:
      level: INFO
      message: Navigating to %2$s
    afterTo:
      message: Navigated to %2$s
    beforeBack:
      level: INFO
      message: Going back
    afterBack:
      message: Went back
    beforeForward:
      level: INFO
      message: Going forward
    afterForward:
      message: Went forward
    beforeRefresh:
      level: INFO
      message: Refreshing page
    afterRefresh:
      message: Page refreshed
    beforeAnyAlertCall:
      message: Calling alert method %2$s with args %3$s
    afterAnyAlertCall:
      message: Alert method %2$s with args %3$s resulted in %4$s
    beforeAccept:
      level: INFO
      message: Accepting alert
    afterAccept:
      message: Alert accepted
    beforeDismiss:
      level: INFO
      message: Dismissing alert
    afterDismiss:
      message: Alert dismissed
    beforeAnyOptionsCall:
      message: Calling options method %2$s with args %3$s
    afterAnyOptionsCall:
      message: Options method %2$s with args %3$s resulted in %4$s
    beforeAddCookie:
      level: TRACE
      message: Adding cookie %2$s
    afterAddCookie:
      message: Added cookie %2$s
    beforeDeleteCookieNamed:
      level: TRACE
      message: Deleting cookie named %2$s
    afterDeleteCookieNamed:
      message: Cookie named %2$s deleted
    beforeDeleteCookie:
      level: TRACE
      message: Deleting cookie %2$s
    afterDeleteCookie:
      message: Cookie %2$s deleted
    beforeDeleteAllCookies:
      level: TRACE
      message: Deleting all cookies
    afterDeleteAllCookies:
      message: All cookies deleted
    beforeGetCookies:
      level: TRACE
      message: Getting cookies
    afterGetCookies:
      message: Cookies are %2$s
    beforeGetCookieNamed:
      level: TRACE
      message: Getting cookie named %2$s
    afterGetCookieNamed:
      message: Cookie named %2$s is %3$s
    beforeAnyTimeoutsCall:
      message: About to reach timeout on method %2$s with args %3$s
    afterAnyTimeoutsCall:
      message: Got timeout on method %2$s with args %3$s and result %4$s
    beforeImplicitlyWait:
      message: Waiting for %2$s
    afterImplicitlyWait:
      message: Waited for %2$s
    beforeSetScriptTimeout:
      message: Setting script timeout to %2$s
    afterSetScriptTimeout:
      message: Script timeout set to %2$s
    beforePageLoadTimeout:
      message: About to reach page load timeout of %2$s
    afterPageLoadTimeout:
      message: Reached page load timeout of %2$s
    beforeAnyWindowCall:
      message: Calling window method %2$s with args %3$s
    afterAnyWindowCall:
      message: Window method %2$s with args %3$s resulted in %4$s
    beforeGetWindowSize:
      message: Getting size of window %1$s
    afterGetWindowSize:
      level: TRACE
      message: Size of window %1$s is %2$s
    beforeSetSize:
      message: Settings size to %2$s
    afterSetSize:
      level: INFO
      message: Set size to %2$s
    beforeGetPosition:
      message: Getting window position
    afterGetPosition:
      level: INFO
      message: Window position is %2$s
    beforeSetPosition:
      message: Setting window position to %2$s
    afterSetPosition:
      level: INFO
      message: Set window position to %2$s
    beforeMaximize:
      level: DEBUG
      message: Maximizing window
    afterMaximize:
      message: Window maximized
    beforeFullscreen:
      level: DEBUG
      message: Setting fullscreen
    afterFullscreen:
      message: Window set to fullscreen

# Data models
data:
  folder: data  # subfolder under src/test/resources where you will save your data*.yaml
  fqdn: fqdn.placeholder  # you need to provide the fully qualified name of your Data class, meaning its package name AND class name.

# FreeMarker template engine configuration. See https://freemarker.apache.org/
freeMarker:
  version: 2.3.32
  locale: US
  numberFormat: 0.##;; roundingMode=halfUp

# Internal event consumers. Cannot be removed, modified, nor added from client side configuration*.yaml.
eventsConsumers:
  - extentTest: # We need to add an entry to the Extent Report once each test is done
      events:
        - reason: after
          tags: [ test ]
  - testbook: # We need to update the TestBook (if configured) once each test is done
      events:
        - reason: after
          tags: [ test ]
  - browser: # We need to close the browser/webDriver once each test is done
      events:
        - reason: after
          tags: [ test ]
  - video: # We need to finalize the video once each test is done
      events:
        - reason: after
          tags: [ test ]
