title: Spectrum
description: Java Selenium 4 Framework
url: https://giulong.github.io
baseurl: /spectrum
github_username: giulong
repository: giulong/spectrum
github:
  repository_url: https://github.com/giulong/spectrum/blob/main
