name: Build

on:
  push:
    branches: [ "develop", "feature/**", "bugfix/**" ]

env:
  EDGE_BINARY: /usr/bin/microsoft-edge

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Building Spectrum
        run: ./mvnw install -DskipSign -Dmaven.plugin.validation=BRIEF -ntp -pl spectrum

  browsers:
    name: Browsers IT
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: mvn browsers tests
        run: ./mvnw install -DskipSign -DallTests -Dmaven.plugin.validation=BRIEF -ntp -pl '!spectrum'

  appium:
    name: Appium IT
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install and Run Appium Server
        run: ./.github/actions/appium.sh

      - name: mvn appium tests
        run: ./mvnw install -DskipSign -DappiumTests -Dmaven.plugin.validation=BRIEF -ntp -pl '!spectrum'
