name: Build

on:
  push:
    branches: [ "develop", "feature/**", "bugfix/**" ]

env:
  EDGE_BINARY: /usr/bin/microsoft-edge

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run in Java
        uses: ./github/actions/run-with-java.yml

      - name: Building Spectrum
        run: ./mvnw install -DskipSign -Dmaven.plugin.validation=BRIEF -ntp -pl spectrum

  browsers:
    name: Browsers IT
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run in Java
        uses: ./github/actions/run-with-java.yml

      - name: mvn browsers tests
        run: ./mvnw install -DskipSign -DallTests -Dmaven.plugin.validation=BRIEF -ntp -pl '!spectrum'

  appium:
    name: Appium IT
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run in Java
        uses: ./github/actions/run-with-java.yml

      - name: Install and Run Appium Server
        run: ./.github/actions/appium.sh

      - name: mvn appium tests
        run: ./mvnw install -DskipSign -DappiumTests -Dmaven.plugin.validation=BRIEF -ntp -pl '!spectrum'
