name: Build

on:
  push:
    branches: [ "develop", "feature/**", "bugfix/**" ]

env:
  EDGE_BINARY: /usr/bin/microsoft-edge

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build Spectrum
        shell: bash
        run: ./mvnw install -DskipSign -Dmaven.plugin.validation=NONE -ntp -P framework-only

      - name: Get Spectrum version
        id: get_version
        run: |
          VERSION=$( ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Spectrum jar cache
        uses: actions/cache@v4
        id: spectrum-cache
        with:
          path: spectrum/target/spectrum-${{ env.version }}.jar
          key: spectrum-jar

  browsers:
    name: Browsers IT
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Restore cached Spectrum jar
        uses: actions/cache/restore@v4
        with:
          path: spectrum-${{ env.version }}.jar
          key: spectrum-jar

      - name: Install Spectrum
        shell: bash
        run: mvn install:install-file -Dfile=spectrum-${{ env.version }}.jar

      - name: Run browsers ITs
        uses: ./.github/actions/maven-build
        with:
          args: -DbrowsersTests
          profiles: browsers

  appium:
    name: Appium IT
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        shell: bash
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd

      - name: Install and Run Appium Server
        run: |
          npm i -g appium
          appium driver install uiautomator2
          appium &>/dev/null &

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: echo "Generated AVD snapshot for caching."

      - name: Restore cached Spectrum jar
        uses: actions/cache/restore@v4
        with:
          path: spectrum-${{ env.version }}.jar
          key: spectrum-jar

      - name: Install Spectrum
        shell: bash
        run: mvn install:install-file -Dfile=spectrum-${{ env.version }}.jar

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          avd-name: phone
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./mvnw install -DskipSign -Dmaven.plugin.validation=NONE -DappiumTests -ntp -pl it-appium
