name: Build

on:
  push:
    branches: [ "develop", "feature/**", "bugfix/**" ]

env:
  EDGE_BINARY: /usr/bin/microsoft-edge

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: mvn install
        run: ./mvnw -B install -DallTests -DskipSign -Dmaven.plugin.validation=BRIEF
