name: Deploy

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]

env:
  DOCS_FOLDER: docs

jobs:
  deploy:
    if: github.event.pull_request.merged
    name: Deploy
    runs-on: ubuntu-latest
    permissions: write-all
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: install-secret-key
        name: Install gpg secret key
        run: cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import

      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./mvnw -B deploy -DskipTests -Dmaven.plugin.validation=BRIEF -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} -ntp

      - name: Get version from pom.xml
        run: |
          VERSION=$( ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "version=$VERSION" >> $GITHUB_ENV
        id: get_version

      - name: Spectrum submodule package
        run: ./mvnw -B package -DskipSign -Dmaven.plugin.validation=BRIEF -ntp -pl spectrum

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: ${{ env.DOCS_FOLDER }}/jacoco/jacoco.csv
          branches-label: Branches
          badges-directory: ${{ env.DOCS_FOLDER }}/badges
          intervals: 95 87.5 75 67.5 60 0
          fail-if-coverage-less-than: 0.9
          fail-if-branches-less-than: 0.9

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: docs/
          destination: ./_site

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
