name: Deploy

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]

jobs:
  deploy:
    if: github.event.pull_request.merged
    name: Deploy
    runs-on: ubuntu-latest
    permissions: write-all
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - uses: actions/checkout@v4

      - id: install-secret-key
        name: Install gpg secret key
        run: cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: ./mvnw -B deploy -DskipTests -Dmaven.plugin.validation=BRIEF -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}

      - name: Get version from pom.xml
        run: |
          VERSION=$( ./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "version=$VERSION" >> $GITHUB_ENV
        id: get_version

      - name: Push json schemas
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.JSON_SCHEMA_DEPLOY_KEY }}
        with:
          source-directory: spectrum/target/json-schemas
          destination-github-username: giulong
          destination-repository-name: spectrum-json-schemas
          user-email: giuliolongfils@gmail.com
          target-branch: main
          target-directory: ${{ env.version }}

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: docs/
          destination: ./_site

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
