name: Docs

on:
  push:
    branches: [ "docs/**" ]

env:
  DOCS_FOLDER: docs

jobs:
  deploy:
    name: Docs
    runs-on: ubuntu-latest
    permissions: write-all
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Spectrum submodule package
        run: ./mvnw -B package -DskipSign -Dmaven.plugin.validation=BRIEF -pl spectrum

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: ${{ env.DOCS_FOLDER }}/jacoco/jacoco.csv
          coverage-label: Coverage
          branches-label: Branches
          badges-directory: ${{ env.DOCS_FOLDER }}/badges
          intervals: 95 87.5 75 67.5 60 0
          fail-if-coverage-less-than: 0.9
          fail-if-branches-less-than: 0.9

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ${{ env.DOCS_FOLDER }}/
          destination: ./_site

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
