name: Docs

on:
  push:
    branches: [ "docs/**" ]

jobs:
  deploy:
    name: Docs
    runs-on: ubuntu-latest
    permissions: write-all
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: docs/
          destination: ./_site

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Spectrum unit tests and JaCoCo reports
        run: ./mvnw -B test -DskipSign -Dmaven.plugin.validation=BRIEF -pl spectrum

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v2

      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
